// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// sdp_caili
List sdp_caili(NumericMatrix S, NumericVector lambda, int maxiter, double tolerance, double admm_penalty, int verbose);
RcppExport SEXP methodcombo_sdp_caili(SEXP SSEXP, SEXP lambdaSEXP, SEXP maxiterSEXP, SEXP toleranceSEXP, SEXP admm_penaltySEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type S(SSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< double >::type tolerance(toleranceSEXP);
    Rcpp::traits::input_parameter< double >::type admm_penalty(admm_penaltySEXP);
    Rcpp::traits::input_parameter< int >::type verbose(verboseSEXP);
    __result = Rcpp::wrap(sdp_caili(S, lambda, maxiter, tolerance, admm_penalty, verbose));
    return __result;
END_RCPP
}
// sdp_gv
List sdp_gv(NumericMatrix S, NumericVector lambda, int maxiter, double tolerance, double admm_penalty, int verbose);
RcppExport SEXP methodcombo_sdp_gv(SEXP SSEXP, SEXP lambdaSEXP, SEXP maxiterSEXP, SEXP toleranceSEXP, SEXP admm_penaltySEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type S(SSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< double >::type tolerance(toleranceSEXP);
    Rcpp::traits::input_parameter< double >::type admm_penalty(admm_penaltySEXP);
    Rcpp::traits::input_parameter< int >::type verbose(verboseSEXP);
    __result = Rcpp::wrap(sdp_gv(S, lambda, maxiter, tolerance, admm_penalty, verbose));
    return __result;
END_RCPP
}
// sdp_mm
List sdp_mm(NumericMatrix S, NumericVector lambda, int maxiter, double tolerance, double admm_penalty, int verbose);
RcppExport SEXP methodcombo_sdp_mm(SEXP SSEXP, SEXP lambdaSEXP, SEXP maxiterSEXP, SEXP toleranceSEXP, SEXP admm_penaltySEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type S(SSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< double >::type tolerance(toleranceSEXP);
    Rcpp::traits::input_parameter< double >::type admm_penalty(admm_penaltySEXP);
    Rcpp::traits::input_parameter< int >::type verbose(verboseSEXP);
    __result = Rcpp::wrap(sdp_mm(S, lambda, maxiter, tolerance, admm_penalty, verbose));
    return __result;
END_RCPP
}
